# Generated by Django 3.1.4 on 2020-12-17 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20201217_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='startdate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
