# Generated by Django 3.1.4 on 2020-12-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20201217_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='startdate',
            field=models.DateField(),
        ),
    ]
